import type { Tool } from './schema';

/**
 * The tool registry: every public tool, defined once. The marketplace, its sections, search,
 * category filters, related tools, families, tool pages and privacy labels all read from here.
 *
 * Adding a tool:
 *   1. add its id to TOOL_IDS (ids.ts) and an entry here;
 *   2. give it artwork (components/marketplace/art.tsx) — TypeScript asks for it;
 *   3. give it an interface (components/marketplace/tool-runtime.tsx), unless it's Coming soon.
 * It then appears everywhere it belongs. `npm test` checks the entry (tests/unit.spec.ts).
 *
 * Copy rules: say what it does in plain words; limits are honest; privacy is a fact about the
 * architecture, never a slogan; "featured", "pick" and "fresh" are editorial, never usage data.
 */
export const tools: Tool[] = [
  /* ---------------- Money ---------------- */
  {
    id: 'split',
    slug: 'split',
    name: 'Split',
    kind: 'Check splitter',
    tagline: 'Split the check fairly, down to the shared fries.',
    description:
      'Add who was there and what everyone had. Shared plates split between the people who shared them, tax and tip land in proportion, and everyone gets their exact total, down to the cent.',
    category: 'money',
    status: 'available',
    visibility: 'public',
    access: 'freemium',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['browser', 'link'],
      note: 'The math runs on your phone. Your bill stays in this browser until you share it.',
    },
    accent: '#b8f35a',
    accentInk: 'dark',
    icon: 'receipt-text',
    keywords: [
      'split the bill',
      'split the check',
      'split dinner',
      'split a check',
      'who owes what',
      'divide the bill',
      'tip calculator',
      'tax and tip',
      'restaurant bill',
      'group dinner',
      'bill splitter',
      'shared plates',
      'dinner with friends',
      'owe money',
      'pay back',
      'even split',
    ],
    aliases: ['splitwise', 'tab', 'check splitter', 'bill split', 'venmo request'],
    related: ['when', 'bring', 'subscriptions'],
    featured: true,
    pick: true,
    fresh: true,
    priority: 10,
    steps: [
      'Add the people at the table.',
      'Add each item and tap who had it. Shared plates split between them.',
      'Set tax and tip, then send everyone their total.',
    ],
    limits: [
      'You type the items in. Reading a receipt photo comes later.',
      'One currency per bill.',
      'The shared summary is read-only: whoever holds the bill makes the changes.',
    ],
    later: [
      { label: 'Snap the receipt instead of typing it', pro: true },
      { label: 'Everyone claims their own items from their phone', pro: false },
    ],
  },
  {
    id: 'subscriptions',
    slug: 'subscriptions',
    name: 'Subscriptions',
    kind: 'Subscription tracker',
    tagline: 'See what your subscriptions really cost.',
    description:
      'List what you pay for — monthly, yearly or every few weeks — and see the real monthly and yearly total, what charges next, and which part of your life it all goes to.',
    category: 'money',
    status: 'available',
    visibility: 'public',
    access: 'freemium',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['browser'],
      note: 'Your list is saved in this browser only. Export it any time; clearing your browser data deletes it.',
    },
    accent: '#7ce0c3',
    accentInk: 'dark',
    icon: 'repeat',
    keywords: [
      'subscriptions',
      'track subscriptions',
      'subscription tracker',
      'cancel subscriptions',
      'recurring payments',
      'monthly bills',
      'how much do i spend',
      'streaming costs',
      'netflix',
      'spotify',
      'gym membership',
      'renewals',
      'free trial ending',
      'yearly cost',
      'what am i paying for',
    ],
    aliases: ['rocket money', 'truebill', 'bobby'],
    related: ['split', 'receipts', 'palette'],
    pick: true,
    fresh: true,
    priority: 20,
    steps: [
      'Add each service, what it costs and how often it charges.',
      'See your true monthly and yearly total, and what charges next.',
      'Keep a note of how to cancel for the day you need it.',
    ],
    limits: [
      'You add subscriptions yourself. Nothing is connected to your bank or email.',
      'Saved in this browser only. Export a copy to move it to another device.',
    ],
    later: [
      { label: 'Find subscriptions in your email receipts (Gmail)', pro: true },
      { label: 'A reminder before a free trial turns paid', pro: false },
    ],
  },
  {
    id: 'receipts',
    slug: 'receipts',
    name: 'Receipts',
    kind: 'Receipt capture and approvals',
    tagline: 'Snap it, check it, file it.',
    description:
      'Photograph a receipt, check the details and file it to the right vehicle or project. Teams get an approval step before anything counts. Built for crews that live on fuel and supplies.',
    category: 'business',
    status: 'soon',
    visibility: 'public',
    access: 'freemium',
    account: 'required',
    privacy: {
      processing: 'server',
      storage: ['account'],
      note: 'Receipts are kept with your team’s account so the people who approve them can see them. Hyphy doesn’t sell your data.',
    },
    accent: '#e4ff3a',
    accentInk: 'dark',
    icon: 'receipt',
    keywords: [
      'receipts',
      'gas receipts',
      'fuel receipts',
      'expense report',
      'scan receipt',
      'reimbursement',
      'expenses',
      'receipt tracker',
      'business expenses',
      'approve expenses',
    ],
    aliases: ['expensify', 'gas receipts portal'],
    related: ['mileage', 'subscriptions', 'split'],
    priority: 90,
    steps: [
      'Take a photo of the receipt from your phone.',
      'Check the total, the station and the gallons.',
      'File it to a vehicle or job; a manager approves it.',
    ],
    limits: ['Arrives with Hyphy accounts: it’s working today inside the Hyphy Spaces preview.'],
    later: [{ label: 'Team approvals, exports and fuel-card reports', pro: true }],
    spaces: 'receipts',
  },
  {
    id: 'mileage',
    slug: 'mileage',
    name: 'Mileage',
    kind: 'Mileage log',
    tagline: 'Log a trip in a few taps.',
    description:
      'Log a trip in a few taps, tie it to a vehicle or project, and keep a dated record for reimbursement or taxes, with round trips counted properly.',
    category: 'business',
    status: 'soon',
    visibility: 'public',
    access: 'freemium',
    account: 'required',
    privacy: {
      processing: 'server',
      storage: ['account'],
      note: 'Trips are kept with your account so they add up across your devices. Hyphy doesn’t sell your data.',
    },
    accent: '#7fd4ff',
    accentInk: 'dark',
    icon: 'route',
    keywords: [
      'mileage',
      'mileage log',
      'mileage tracker',
      'miles for taxes',
      'irs mileage',
      'trip log',
      'reimbursement miles',
      'odometer',
      'business miles',
      'drive log',
    ],
    aliases: ['mileiq', 'everlance'],
    related: ['receipts', 'subscriptions', 'split'],
    priority: 91,
    steps: [
      'Type the miles, or the start and end readings.',
      'Tap round trip if you drove back.',
      'Export the month for reimbursement or taxes.',
    ],
    limits: ['Arrives with Hyphy accounts: it’s working today inside the Hyphy Spaces preview.'],
    later: [{ label: 'Team approvals and monthly reports', pro: true }],
    spaces: 'mileage',
  },

  /* ---------------- Gather ---------------- */
  {
    id: 'when',
    slug: 'when',
    name: 'When?',
    kind: 'Availability matcher',
    tagline: 'Find the time that works for everyone.',
    description:
      'Pick the days, share one link, and everyone paints the hours they’re free. The times that work for the most people rise to the top. No accounts, no back-and-forth.',
    category: 'together',
    family: 'gather',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['link', 'browser'],
      note: 'The plan and everyone’s times travel inside the link. Hyphy’s servers never receive them.',
    },
    accent: '#ffb35c',
    accentInk: 'dark',
    icon: 'calendar-clock',
    keywords: [
      'when are my friends free',
      'when is everyone free',
      'find a time',
      'find a time to meet',
      'schedule a meeting',
      'availability',
      'group availability',
      'best time to meet',
      'group schedule',
      'plan a hangout',
      'meeting time',
      'calendar poll',
      'overlap',
      'free time',
      'when works',
    ],
    aliases: ['when2meet', 'doodle', 'availability poll', 'scheduling poll', 'lettucemeet'],
    related: ['bring', 'split', 'where'],
    featured: true,
    fresh: true,
    priority: 12,
    steps: [
      'Pick the days and the hours you’re considering.',
      'Share the link. Each person paints when they’re free.',
      'See where everyone overlaps, then pick the time.',
    ],
    limits: [
      'The plan lives in its link: after adding their times, people send the updated link back.',
      'Up to 14 days and 24 people in one plan.',
      'Times are in the organizer’s time zone, shown on every plan.',
    ],
    later: [{ label: 'One live link that updates for everyone', pro: false }],
  },
  {
    id: 'bring',
    slug: 'bring',
    name: 'Bring',
    kind: 'Shared supply list',
    tagline: 'Who’s bringing what, before three people bring chips.',
    description:
      'List what the party needs, share one link, and let everyone claim what they’ll bring. Made for cookouts, potlucks, trips and dinners where nobody wants a spreadsheet.',
    category: 'together',
    family: 'gather',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['link', 'browser'],
      note: 'The list and its claims travel inside the link. Hyphy’s servers never receive them.',
    },
    accent: '#ffd166',
    accentInk: 'dark',
    icon: 'basket',
    keywords: [
      'potluck',
      'who is bringing what',
      'who brings what',
      'bring list',
      'party supplies',
      'cookout list',
      'shared shopping list',
      'shared grocery list',
      'claim items',
      'bbq',
      'camping list',
      'sign up sheet',
      'dish sign up',
      'party list',
      'what to bring',
    ],
    aliases: ['potluck sign up', 'signup genius', 'perfect potluck'],
    related: ['when', 'split', 'wishlist'],
    fresh: true,
    priority: 14,
    steps: [
      'List what you need: drinks, sides, ice, a speaker.',
      'Share the link with everyone coming.',
      'People claim what they’ll bring; the gaps stay obvious.',
    ],
    limits: [
      'The list lives in its link: after claiming, people send the updated link back.',
      'Up to 80 items in one list.',
    ],
    later: [{ label: 'One live link that updates for everyone', pro: false }],
  },
  {
    id: 'where',
    slug: 'where',
    name: 'Where?',
    kind: 'Group food decider',
    tagline: 'Decide where to eat, without the group-chat spiral.',
    description:
      'Everyone weighs in on cuisine, price and distance, and Where? finds the place the group can actually agree on.',
    category: 'together',
    family: 'gather',
    status: 'soon',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: { processing: 'device', storage: ['link'] },
    accent: '#ff7e5f',
    accentInk: 'dark',
    icon: 'utensils',
    keywords: [
      'what should we eat',
      'where should we eat',
      'where to eat',
      'pick a restaurant',
      'restaurant picker',
      'food decider',
      'dinner ideas',
      'hungry',
      'cuisine',
      'group dinner vote',
    ],
    aliases: ['food roulette'],
    related: ['when', 'split', 'bring'],
    priority: 60,
    steps: [
      'Start a round and share the link.',
      'Everyone picks cuisines, a price and how far they’ll go.',
      'Where? shows the places the group agrees on.',
    ],
    limits: [],
    later: [],
  },
  {
    id: 'plan',
    slug: 'plan',
    name: 'Plan',
    kind: 'Lightweight event planner',
    tagline: 'The occasion, the time, the place and who’s in.',
    description:
      'A simple page for a party or a trip: the occasion, when and where, who’s coming, what to bring and the links everyone needs. Connected to When? and Bring, without becoming a project.',
    category: 'together',
    family: 'gather',
    status: 'soon',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: { processing: 'device', storage: ['link'] },
    accent: '#f7a1c4',
    accentInk: 'dark',
    icon: 'party',
    keywords: [
      'plan a party',
      'event planner',
      'plan an event',
      'birthday party',
      'party planning',
      'rsvp',
      'gathering',
      'trip planning',
      'invite friends',
    ],
    aliases: ['partiful', 'evite'],
    related: ['when', 'bring', 'split'],
    priority: 61,
    steps: [],
    limits: [],
    later: [],
  },

  /* ---------------- Signal ---------------- */
  {
    id: 'qr',
    slug: 'qr',
    name: 'QR Studio',
    kind: 'QR code maker',
    tagline: 'Codes for links, Wi-Fi, contacts and more — styled, and still scannable.',
    description:
      'Make a QR code for a link, your Wi-Fi, a contact card, a phone number, an email or a text. Style the dots, corners and colors, add a logo, and download a print-ready PNG or SVG.',
    category: 'links',
    family: 'signal',
    status: 'available',
    visibility: 'public',
    access: 'freemium',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Codes are drawn on your device. No tracking redirect is ever put inside your code.',
    },
    accent: '#20d392',
    accentInk: 'dark',
    icon: 'qr',
    keywords: [
      'make a qr',
      'qr code',
      'qr code generator',
      'wifi qr',
      'wifi password',
      'share wifi',
      'contact qr',
      'vcard',
      'business card qr',
      'menu qr',
      'qr for a link',
      'qr with logo',
      'qr code for text',
      'scan code',
      'custom qr',
    ],
    aliases: ['qr generator', 'qr maker', 'qr monkey'],
    related: ['signal-links', 'signal-pages', 'palette'],
    featured: true,
    priority: 11,
    steps: [
      'Choose what the code opens: a link, Wi-Fi, a contact, a call, a text.',
      'Style it. Contrast and logo size are checked so it still scans.',
      'Download a sharp PNG or a vector SVG for print.',
    ],
    limits: [
      'Static codes: what’s printed can’t be changed later, and nothing is tracked.',
      'Logos need high error correction, which makes the code denser.',
    ],
    later: [{ label: 'Codes you can change after printing, with scan counts', pro: true }],
    spaces: 'qr',
  },
  {
    id: 'signal-pages',
    slug: 'signal-pages',
    name: 'Signal Pages',
    kind: 'Link-in-bio page',
    tagline: 'One page for everything you link to.',
    description:
      'Build a link-in-bio page with your name, links and socials, in a design that doesn’t look like everyone else’s. Share it as a link or print its QR code.',
    category: 'links',
    family: 'signal',
    status: 'beta',
    visibility: 'public',
    access: 'freemium',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['link', 'browser'],
      note: 'Your page is carried inside its own link, so Hyphy doesn’t store it. Anyone with the link can see it.',
    },
    accent: '#ff8ad8',
    accentInk: 'dark',
    icon: 'link',
    keywords: [
      'link in bio',
      'bio link',
      'link page',
      'links page',
      'instagram bio link',
      'tiktok bio link',
      'all my links',
      'one link for everything',
      'social links',
      'personal page',
      'landing page',
    ],
    aliases: ['linktree', 'beacons', 'link hub', 'lnk bio', 'carrd', 'bio site'],
    related: ['qr', 'signal-links', 'palette'],
    pick: true,
    priority: 15,
    steps: [
      'Tap your name, bio and links on the phone to edit them.',
      'Pick a design and add your socials.',
      'Share the page’s link, or print its QR code.',
    ],
    limits: [
      'Your page lives in a long link for now. A short address arrives with accounts.',
      'Up to 12 links and 8 socials.',
    ],
    later: [
      { label: 'A short, custom address for your page', pro: false },
      { label: 'Click counts for every link', pro: true },
      { label: 'Photos, embeds and more designs', pro: true },
    ],
    spaces: 'links',
  },
  {
    id: 'signal-links',
    slug: 'signal-links',
    name: 'Signal Links',
    kind: 'Campaign link builder',
    tagline: 'Make a link that tells you where your visitors came from.',
    description:
      'Turn any link into a trackable campaign link for a post, an email or a flyer. Your analytics can then show which one actually brought people in. Plain words first, the technical fields when you want them.',
    category: 'links',
    family: 'signal',
    status: 'available',
    visibility: 'public',
    access: 'freemium',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['browser'],
      note: 'Links are built on your device. The link you’re making and your recent links are remembered in this browser only.',
    },
    accent: '#8f9bff',
    accentInk: 'dark',
    icon: 'link-2',
    keywords: [
      'utm',
      'utm builder',
      'utm generator',
      'utm link',
      'campaign link',
      'tracking link',
      'trackable link',
      'track a link',
      'google analytics link',
      'track clicks',
      'marketing link',
      'source medium campaign',
      'where did visitors come from',
    ],
    aliases: ['campaign url builder', 'url builder', 'utm.io'],
    related: ['qr', 'signal-pages', 'social-crop'],
    fresh: true,
    priority: 30,
    steps: [
      'Paste the page you’re sending people to.',
      'Say where the link will live: an Instagram post, a newsletter, a flyer.',
      'Copy the finished link, or turn it into a QR code.',
    ],
    limits: [
      'Tracking shows up in your own analytics (like Google Analytics). Hyphy doesn’t count clicks.',
      'Doesn’t shorten links yet.',
    ],
    later: [{ label: 'Short links with click counts', pro: true }],
  },

  /* ---------------- File Lab ---------------- */
  {
    id: 'pdf',
    slug: 'pdf',
    name: 'PDF',
    kind: 'PDF toolkit',
    tagline: 'Merge, split, reorder, rotate and pull out pages.',
    description:
      'Combine PDFs, keep only the pages you need, split one into several, or fix the order and the sideways scans, with every page shown as it really looks.',
    category: 'files',
    family: 'file-lab',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Your PDFs are opened and rebuilt in your browser. They’re never uploaded.',
    },
    accent: '#ff6a3d',
    accentInk: 'dark',
    icon: 'pdf',
    keywords: [
      'merge pdf',
      'combine pdf',
      'join pdf',
      'split pdf',
      'extract pages',
      'remove pages from pdf',
      'delete pdf pages',
      'rotate pdf',
      'reorder pdf pages',
      'organize pdf',
      'pdf pages',
      'one pdf',
    ],
    aliases: ['ilovepdf', 'smallpdf', 'pdf merge', 'pdf splitter', 'adobe acrobat'],
    related: ['convert', 'clean', 'duplicates'],
    pick: true,
    priority: 13,
    steps: [
      'Choose what to do: merge, organize, keep pages or split.',
      'Drop in your PDFs and see every page.',
      'Download the new PDF.',
    ],
    limits: [
      'Up to 20 files, 50 MB and 500 pages at a time.',
      'Pages are copied as they are: form fields, bookmarks and signatures may not carry over.',
      'Password-protected PDFs can’t be opened.',
    ],
    later: [],
    spaces: 'pdf',
  },
  {
    id: 'convert',
    slug: 'convert',
    name: 'Convert',
    kind: 'Images to PDF and back',
    tagline: 'Photos into one PDF, or PDF pages into images.',
    description:
      'Turn photos and scans into a single PDF, in the order you choose, or turn the pages of a PDF into sharp JPG or PNG images.',
    category: 'files',
    family: 'file-lab',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Converted in your browser. Nothing is uploaded, and camera details and location are left out of the PDF.',
    },
    accent: '#ff9a62',
    accentInk: 'dark',
    icon: 'file-stack',
    keywords: [
      'jpg to pdf',
      'image to pdf',
      'photos to pdf',
      'png to pdf',
      'scan to pdf',
      'pdf to jpg',
      'pdf to image',
      'pdf to png',
      'convert pdf',
      'convert images',
      'make a pdf',
    ],
    aliases: ['img2pdf'],
    related: ['pdf', 'resize', 'clean'],
    fresh: true,
    priority: 32,
    steps: [
      'Choose a direction: images to PDF, or PDF to images.',
      'Add your files and put them in order.',
      'Download the PDF, or the images in one zip.',
    ],
    limits: [
      'Reads JPG, PNG, WebP, GIF and AVIF. iPhone HEIC photos open only in Safari.',
      'Up to 60 images (40 MB each), or one PDF of up to 200 pages and 50 MB.',
      'Password-protected PDFs can’t be opened.',
      'Page images are pictures: links, forms and selectable text don’t carry over.',
    ],
    later: [],
  },
  {
    id: 'clean',
    slug: 'clean',
    name: 'Clean',
    kind: 'Bulk file renamer',
    tagline: 'Rename a pile of files at once, and see every new name first.',
    description:
      'Clean up file names with find and replace, numbering, prefixes, dates and tidy capitalization. Every new name is previewed before anything happens, then you download renamed copies in one zip.',
    category: 'files',
    family: 'file-lab',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Your files are read and zipped in your browser. They’re never uploaded.',
    },
    accent: '#c7b5ff',
    accentInk: 'dark',
    icon: 'replace',
    keywords: [
      'rename files',
      'bulk rename',
      'batch rename',
      'rename photos',
      'rename many files',
      'file names',
      'clean up file names',
      'clean some files',
      'number files',
      'find and replace file names',
      'lowercase file names',
      'remove spaces from file names',
      'img files',
    ],
    aliases: ['bulk rename utility', 'renamer', 'file renamer', 'advanced renamer'],
    related: ['duplicates', 'pdf', 'convert'],
    fresh: true,
    priority: 31,
    steps: [
      'Choose your files, or a whole folder.',
      'Stack up rules: replace, number, add a date, fix capitals.',
      'Check every new name, then download the renamed copies.',
    ],
    limits: [
      'Browsers can’t rename files where they sit, so you download renamed copies in a zip.',
      'Up to 1,000 files and 1 GB at a time.',
      'Dates come from each file’s last-modified time, which isn’t always when a photo was taken.',
    ],
    later: [],
  },
  {
    id: 'duplicates',
    slug: 'duplicates',
    name: 'Duplicates',
    kind: 'Duplicate file finder',
    tagline: 'Find the files you have twice.',
    description:
      'Choose a folder or a pile of files and Duplicates finds exact copies by what’s inside them, even when the names are different, and shows how much space they take.',
    category: 'files',
    family: 'file-lab',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Files are fingerprinted in your browser. Nothing is uploaded, and nothing is deleted.',
    },
    accent: '#9fb2ff',
    accentInk: 'dark',
    icon: 'copy',
    keywords: [
      'duplicate files',
      'find duplicates',
      'duplicate photos',
      'same file twice',
      'remove duplicates',
      'free up space',
      'dedupe',
      'identical files',
      'copies of files',
      'find copies',
    ],
    aliases: ['dupeguru', 'gemini duplicate finder'],
    related: ['clean', 'resize', 'pdf'],
    fresh: true,
    priority: 33,
    steps: [
      'Choose a folder, or select a pile of files.',
      'Duplicates compares what’s inside each file.',
      'See every group of copies and download the list.',
    ],
    limits: [
      'Checks only the files you choose. It can’t scan your whole computer.',
      'Finds exact copies. Photos that only look alike come later.',
      'It never deletes anything. You get a clear list to clean up yourself.',
      'Files over 2 GB can’t be read in a browser. When two share a size, they’re listed for you to compare by hand.',
    ],
    later: [{ label: 'Photos that look alike, not just exact copies', pro: false }],
  },

  /* ---------------- Image Lab ---------------- */
  {
    id: 'resize',
    slug: 'resize',
    name: 'Resize & Compress',
    kind: 'Image resizer and compressor',
    tagline: 'Smaller files. Same picture.',
    description:
      'Resize, compress and convert photos to JPG, PNG or WebP, and see the new size before you download. A file never comes back bigger than it went in.',
    category: 'images',
    family: 'image-lab',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Photos are processed in your browser. Saved copies leave out camera and location data.',
    },
    accent: '#ffc53d',
    accentInk: 'dark',
    icon: 'image',
    keywords: [
      'resize photos',
      'resize image',
      'compress image',
      'compress photos',
      'reduce image size',
      'make photo smaller',
      'shrink photo',
      'image file size',
      'convert image',
      'jpg to webp',
      'png to jpg',
      'optimize images',
      'photo too big',
    ],
    aliases: ['tinypng', 'squoosh', 'image compressor', 'image resize'],
    related: ['social-crop', 'palette', 'convert'],
    priority: 16,
    steps: [
      'Drop in up to 20 photos.',
      'Pick a width, a format and a quality.',
      'Compare the sizes, then download.',
    ],
    limits: ['Up to 20 images at a time, 40 MB each.', 'Images are never enlarged.'],
    later: [],
    spaces: 'images',
  },
  {
    id: 'social-crop',
    slug: 'social-crop',
    name: 'Social Crop',
    kind: 'Social media image sizes',
    tagline: 'One photo, framed for every feed.',
    description:
      'Add a photo once and frame it for Instagram, Stories, TikTok, YouTube, X and LinkedIn. Drag and zoom to compose each size, then download one or all of them.',
    category: 'images',
    family: 'image-lab',
    status: 'available',
    visibility: 'public',
    access: 'freemium',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Your photo is framed and exported in your browser. It’s never uploaded.',
    },
    accent: '#ff9e7a',
    accentInk: 'dark',
    icon: 'crop',
    keywords: [
      'instagram size',
      'instagram post size',
      'instagram story size',
      'crop for instagram',
      'tiktok size',
      'youtube thumbnail',
      'social media sizes',
      'resize for social media',
      'reel cover',
      'linkedin banner',
      'x header',
      'twitter header',
      'crop photo',
      'crop image',
      'aspect ratio',
      'square photo',
      'profile picture',
    ],
    aliases: ['social image resizer', 'crop tool'],
    related: ['resize', 'palette', 'signal-links'],
    featured: true,
    fresh: true,
    priority: 17,
    steps: [
      'Add one photo.',
      'Pick the sizes you need and drag each frame to compose it.',
      'Download one, or all of them in a zip.',
    ],
    limits: [
      'Cropping removes what falls outside a frame. Fit mode keeps it all, with a soft backdrop.',
      'Exports JPG or PNG at each network’s recommended size.',
    ],
    later: [
      { label: 'AI Expand: grow a photo to fit a new shape instead of cropping it', pro: true },
    ],
  },
  {
    id: 'palette',
    slug: 'palette',
    name: 'Palette',
    kind: 'Color palette extractor',
    tagline: 'Pull the colors out of any image.',
    description:
      'Drop in a photo or a logo and get its key colors as HEX and RGB, ready-to-paste CSS variables, and which pairs are readable together.',
    category: 'images',
    family: 'image-lab',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Colors are measured in your browser. Your image is never uploaded.',
    },
    accent: '#a78bfa',
    accentInk: 'dark',
    icon: 'palette',
    keywords: [
      'color palette',
      'colors from image',
      'colors from logo',
      'hex codes',
      'hex color',
      'brand colors',
      'extract colors',
      'color picker',
      'css variables',
      'color scheme',
      'rgb values',
      'what color is this',
    ],
    aliases: ['coolors', 'adobe color', 'eyedropper', 'colorthief'],
    related: ['qr', 'signal-pages', 'social-crop'],
    fresh: true,
    priority: 18,
    steps: [
      'Drop in a photo or a logo.',
      'Get its key colors, strongest first.',
      'Copy HEX, RGB, HSL, CSS or a Tailwind theme, or download the swatches.',
    ],
    limits: [
      'Finds up to 10 key colors. Tiny details may not make the cut, so tap the image to add them.',
    ],
    later: [],
  },

  /* ---------------- Drops ---------------- */
  {
    id: 'wishlist',
    slug: 'christmas-list',
    name: 'Christmas List',
    kind: 'Shareable wish list',
    tagline: 'A wish list that quietly stops duplicate gifts.',
    description:
      'Make a list with links, prices and notes. Family and friends claim what they’re buying, and you never see who got what, so the surprise survives.',
    category: 'together',
    drop: {
      season: 'Holiday 2026',
      line: 'For everyone who has ever received two identical sweaters.',
    },
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['link', 'browser'],
      note: 'The list and the claims travel inside links. Hyphy’s servers never receive them.',
    },
    accent: '#ff5e57',
    accentInk: 'dark',
    icon: 'gift',
    keywords: [
      'christmas list',
      'wish list',
      'wishlist',
      'gift list',
      'gift ideas',
      'birthday wishlist',
      'holiday list',
      'present list',
      'santa list',
      'who is buying what',
      'registry',
      'gift registry',
    ],
    aliases: ['giftster', 'elfster', 'amazon wishlist'],
    related: ['secret-santa', 'bring', 'split'],
    featured: true,
    fresh: true,
    priority: 19,
    steps: [
      'Add what you’d love: a link, a price, a note, how much you want it.',
      'Share the gift-giver link with family and friends, not with yourself.',
      'They claim gifts; your own link never shows who claimed what.',
    ],
    limits: [
      'Claims live in the gift-giver link: after claiming, givers pass the updated link along.',
      'Up to 60 items in one list.',
    ],
    later: [{ label: 'One live list that updates for everyone', pro: false }],
  },
  {
    id: 'secret-santa',
    slug: 'secret-santa',
    name: 'Secret Santa',
    kind: 'Gift exchange draw',
    tagline: 'Draw names without a hat, or spoilers.',
    description:
      'Add everyone, set who shouldn’t draw whom, and send each person a private link with only their match.',
    category: 'together',
    drop: { season: 'Holiday 2026', line: 'Drawing names, minus the hat.' },
    status: 'soon',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: { processing: 'device', storage: ['link'] },
    accent: '#46c28e',
    accentInk: 'dark',
    icon: 'ticket',
    keywords: [
      'secret santa',
      'gift exchange',
      'draw names',
      'white elephant',
      'kris kringle',
      'name draw',
    ],
    aliases: ['elfster', 'drawnames'],
    related: ['wishlist', 'bring', 'split'],
    priority: 62,
    steps: [],
    limits: [],
    later: [],
  },
];
