import type { Tool } from './schema';

/**
 * The tool registry: every public tool, defined once. The marketplace, its sections, search,
 * category filters, related tools, families, tool pages and privacy labels all read from here.
 *
 * Adding a tool:
 *   1. add its id to TOOL_IDS (ids.ts) and an entry here;
 *   2. give it artwork (components/marketplace/art.tsx) — TypeScript asks for it;
 *   3. give it an interface (components/marketplace/tool-runtime.tsx), unless it's Coming soon.
 * It then appears everywhere it belongs. `npm test` checks the entry (tests/unit.spec.ts).
 *
 * Copy rules: say what it does in plain words; limits are honest; privacy is a fact about the
 * architecture, never a slogan; "featured", "pick" and "fresh" are editorial, never usage data.
 */
export const tools: Tool[] = [
  /* ---------------- Money ---------------- */
  {
    id: 'split',
    slug: 'split',
    name: 'Split',
    kind: 'Check splitter',
    tagline: 'Snap the receipt. Everyone gets their exact total.',
    description:
      'Take a photo of the check and Split reads the items and prices for you to check. Tap who had what, pick a tip, and everyone gets their exact total, down to the cent. Shared plates split between the people who shared them; tax and tip land in proportion.',
    category: 'money',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['browser', 'link'],
      note: 'Receipt photos are read on your phone and never uploaded. Your bill stays in this browser until you share it.',
    },
    accent: '#b8f35a',
    accentInk: 'dark',
    icon: 'receipt-text',
    keywords: [
      'split the bill',
      'split the check',
      'split dinner',
      'split a check',
      'who owes what',
      'divide the bill',
      'tip calculator',
      'tax and tip',
      'restaurant bill',
      'group dinner',
      'bill splitter',
      'shared plates',
      'dinner with friends',
      'owe money',
      'pay back',
      'even split',
      'scan receipt',
      'receipt photo',
      'read a receipt',
    ],
    aliases: ['splitwise', 'tab', 'check splitter', 'bill split', 'venmo request'],
    related: ['when', 'bring', 'subscriptions'],
    featured: true,
    pick: true,
    fresh: true,
    priority: 10,
    modes: {
      everyday: { rank: 1, line: 'Dinner, trips, anything shared' },
      work: { rank: 10, line: 'Team lunches, down to the cent' },
    },
    tier: 'experience',
    steps: [
      'Take a photo of the receipt, or type the items in.',
      'Fix anything that was read wrong, and add who’s at the table.',
      'Tap who had what, pick a tip, and share everyone’s total.',
    ],
    limits: [
      'Receipt reading works best on a flat, sharp photo of a printed receipt. Always give it a quick check.',
      'Discounts and handwritten tips aren’t read yet: add or fix them by hand.',
      'One currency per bill.',
      'The shared summary is read-only: whoever holds the bill makes the changes.',
    ],
    later: [{ label: 'Everyone claims their own items from their phone', pro: false }],
  },
  {
    id: 'subscriptions',
    slug: 'subscriptions',
    name: 'Subscriptions',
    kind: 'Subscription tracker',
    tagline: 'See what your subscriptions really cost.',
    description:
      'List what you pay for — monthly, yearly or every few weeks — and see the real monthly and yearly total, what charges next, and which part of your life it all goes to.',
    category: 'money',
    status: 'available',
    visibility: 'public',
    access: 'freemium',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['browser'],
      note: 'Your list is saved in this browser only. Export it any time; clearing your browser data deletes it.',
    },
    accent: '#7fb6ff',
    accentInk: 'dark',
    icon: 'repeat',
    keywords: [
      'subscriptions',
      'track subscriptions',
      'subscription tracker',
      'cancel subscriptions',
      'recurring payments',
      'monthly bills',
      'how much do i spend',
      'streaming costs',
      'netflix',
      'spotify',
      'gym membership',
      'renewals',
      'free trial ending',
      'yearly cost',
      'what am i paying for',
    ],
    aliases: ['rocket money', 'truebill', 'bobby'],
    related: ['split', 'receipts', 'palette'],
    pick: true,
    fresh: true,
    priority: 20,
    modes: {
      everyday: { rank: 12, line: 'What you really pay each month' },
      work: { rank: 6, line: 'Every tool the business pays for' },
    },
    tier: 'experience',
    steps: [
      'Add each service, what it costs and how often it charges.',
      'See your true monthly and yearly total, and what charges next.',
      'Keep a note of how to cancel for the day you need it.',
    ],
    limits: [
      'You add subscriptions yourself. Nothing is connected to your bank or email.',
      'Saved in this browser only. Export a copy to move it to another device.',
    ],
    later: [
      { label: 'Find subscriptions in your email receipts (Gmail)', pro: true },
      { label: 'A reminder before a free trial turns paid', pro: false },
    ],
  },
  {
    id: 'receipts',
    slug: 'receipts',
    name: 'Receipts',
    kind: 'Receipt scanner and expense log',
    tagline: 'Snap it, check it, filed.',
    description:
      'Take a photo of a receipt and Receipts reads the store, the total, the tax, the date and the card for you to check, then suggests a category. Saved receipts stack up by month with their totals, easy to search, fix and export as a spreadsheet.',
    category: 'business',
    status: 'available',
    visibility: 'public',
    access: 'freemium',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['browser'],
      note: 'Receipts are read on your device and kept in this browser, photos included. Nothing is uploaded.',
    },
    accent: '#1f8a5b',
    accentInk: 'light',
    icon: 'receipt',
    keywords: [
      'receipts',
      'gas receipts',
      'fuel receipts',
      'expense report',
      'scan receipt',
      'receipt scanner',
      'reimbursement',
      'expenses',
      'receipt tracker',
      'business expenses',
      'track expenses',
      'receipt photo',
      'tax receipts',
      'expense log',
    ],
    aliases: ['expensify', 'gas receipts portal', 'shoeboxed'],
    related: ['mileage', 'subscriptions', 'split'],
    fresh: true,
    priority: 21,
    modes: {
      work: { rank: 1, line: 'Snap it, check it, filed' },
    },
    tier: 'experience',
    steps: [
      'Take a photo of the receipt (or choose one, or a PDF).',
      'It’s read on your phone: check the total, the store and the date.',
      'Tap a category and it’s filed by month, ready to export.',
    ],
    limits: [
      'Receipts are kept in this browser, on this device: export a CSV to keep a copy elsewhere.',
      'Reading works best on a flat, well-lit photo; anything it misses is one tap to type.',
      'The first scan downloads the reader (about 4 MB), then it works offline.',
    ],
    later: [
      { label: 'Kept with your Hyphy account, on every device', pro: false },
      { label: 'Team approvals and fuel-card reports', pro: true },
    ],
    spaces: 'receipts',
  },

  {
    id: 'mileage',
    slug: 'mileage',
    name: 'Mileage',
    kind: 'Mileage tracker and log',
    tagline: 'Start drive. Stop. Logged.',
    description:
      'Tap Start drive when you pull out and Stop when you arrive: the miles count up from your phone’s location, then one tap says it was business, personal, medical or charity. Type a trip in by hand or repeat a route you drive often. Trips add up by month and export as a spreadsheet.',
    category: 'business',
    status: 'available',
    visibility: 'public',
    access: 'freemium',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['browser'],
      note: 'Your location is used on your phone while a drive is running and never sent anywhere. Trips are kept in this browser.',
    },
    accent: '#2fd07a',
    accentInk: 'dark',
    icon: 'route',
    keywords: [
      'mileage',
      'mileage log',
      'mileage tracker',
      'track miles',
      'miles for taxes',
      'irs mileage',
      'trip log',
      'reimbursement miles',
      'odometer',
      'business miles',
      'drive log',
      'gps mileage',
      'log a drive',
      'work miles',
    ],
    aliases: ['mileiq', 'everlance', 'stride'],
    related: ['receipts', 'subscriptions', 'split'],
    fresh: true,
    priority: 22,
    modes: {
      work: { rank: 2, line: 'Every business mile, logged' },
    },
    tier: 'experience',
    steps: [
      'Tap Start drive as you leave; keep the page open.',
      'Tap Stop when you arrive and pick what it was for.',
      'Or type a trip in. Export any month as a CSV.',
    ],
    limits: [
      'Measuring works while the page is open with the screen on: phones pause location for pages in the background.',
      'Trips are kept in this browser, on this device: export a CSV to keep a copy elsewhere.',
      'GPS can drift; every trip’s miles can be corrected by hand.',
    ],
    later: [
      { label: 'Kept with your Hyphy account, on every device', pro: false },
      { label: 'Team approvals and monthly reports', pro: true },
    ],
    spaces: 'mileage',
  },

  /* ---------------- Gather ---------------- */
  {
    id: 'when',
    slug: 'when',
    name: 'When?',
    kind: 'Availability matcher',
    tagline: 'Find the time that works for everyone.',
    description:
      'Pick the days, share one link, and everyone paints the hours they’re free. The times that work for the most people rise to the top. No accounts, no back-and-forth.',
    category: 'together',
    family: 'gather',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['link', 'browser'],
      note: 'The plan and everyone’s times travel inside the link. Hyphy’s servers never receive them.',
    },
    accent: '#ffb35c',
    accentInk: 'dark',
    icon: 'calendar-clock',
    keywords: [
      'when are my friends free',
      'when is everyone free',
      'find a time',
      'find a time to meet',
      'schedule a meeting',
      'availability',
      'group availability',
      'best time to meet',
      'group schedule',
      'plan a hangout',
      'meeting time',
      'calendar poll',
      'overlap',
      'free time',
      'when works',
    ],
    aliases: ['when2meet', 'doodle', 'availability poll', 'scheduling poll', 'lettucemeet'],
    related: ['bring', 'split', 'where'],
    featured: true,
    fresh: true,
    priority: 12,
    modes: {
      everyday: { rank: 3, line: 'The night everyone’s free' },
    },
    tier: 'experience',
    steps: [
      'Pick the days and the hours you’re considering.',
      'Share the link. Each person paints when they’re free.',
      'See where everyone overlaps, then pick the time.',
    ],
    limits: [
      'The plan lives in its link: after adding their times, people send the updated link back.',
      'Up to 14 days and 24 people in one plan.',
      'Times are in the organizer’s time zone, shown on every plan.',
    ],
    later: [{ label: 'One live link that updates for everyone', pro: false }],
  },
  {
    id: 'bring',
    slug: 'bring',
    name: 'Bring',
    kind: 'Shared supply list',
    tagline: 'Who’s bringing what, before three people bring chips.',
    description:
      'List what the party needs, share one link, and let everyone claim what they’ll bring. Made for cookouts, potlucks, trips and dinners where nobody wants a spreadsheet.',
    category: 'together',
    family: 'gather',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['link', 'browser'],
      note: 'The list and its claims travel inside the link. Hyphy’s servers never receive them.',
    },
    accent: '#8ee0a0',
    accentInk: 'dark',
    icon: 'basket',
    keywords: [
      'potluck',
      'who is bringing what',
      'who brings what',
      'bring list',
      'party supplies',
      'cookout list',
      'shared shopping list',
      'shared grocery list',
      'claim items',
      'bbq',
      'camping list',
      'sign up sheet',
      'dish sign up',
      'party list',
      'what to bring',
    ],
    aliases: ['potluck sign up', 'signup genius', 'perfect potluck'],
    related: ['when', 'split', 'wishlist'],
    fresh: true,
    priority: 14,
    modes: {
      everyday: { rank: 8, line: 'Potlucks, picnics, cookouts' },
    },
    tier: 'experience',
    steps: [
      'List what you need: drinks, sides, ice, a speaker.',
      'Share the link with everyone coming.',
      'People claim what they’ll bring; the gaps stay obvious.',
    ],
    limits: [
      'The list lives in its link: after claiming, people send the updated link back.',
      'Up to 80 items in one list.',
    ],
    later: [{ label: 'One live link that updates for everyone', pro: false }],
  },
  {
    id: 'where',
    slug: 'where',
    name: 'Where?',
    kind: 'Group place picker',
    tagline: 'Where should we go? Everyone votes, the winner is obvious.',
    description:
      'Ask where to go, drop in a few places (type a name, paste a Google Maps or Yelp link, or tap an idea) and send one link. Everyone taps Love it, Works for me or Not this one, and the favorite rises to the top with directions ready. Restaurants, bars, coffee, date night, things to do or the next trip.',
    category: 'together',
    family: 'gather',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['link', 'browser'],
      note: 'The places and everyone’s votes travel inside the link. Nothing is looked up and Hyphy’s servers never receive them.',
    },
    accent: '#ff6b5b',
    accentInk: 'dark',
    icon: 'map-pin',
    keywords: [
      'what should we eat',
      'where should we eat',
      'where should we go',
      'where to eat',
      'pick a restaurant',
      'restaurant picker',
      'food decider',
      'dinner ideas',
      'hungry',
      'cuisine',
      'group dinner vote',
      'vote on a restaurant',
      'where to go tonight',
      'bar',
      'drinks',
      'coffee',
      'date night',
      'things to do',
      'group outing',
      'vacation ideas',
      'place poll',
    ],
    aliases: ['food roulette', 'restaurant poll', 'place vote'],
    related: ['plan', 'when', 'split'],
    fresh: true,
    priority: 13,
    modes: {
      everyday: { rank: 7, line: 'Let the group vote on a place' },
    },
    tier: 'experience',
    steps: [
      'Ask the question and add a few places: a name, a Maps or Yelp link, or an idea.',
      'Send the link. People tap Love it, Works for me or Not this one, then send it back.',
      'The favorite rises to the top, with directions and a way to add it to a Plan.',
    ],
    limits: [
      'The round lives in its link: after voting, people send the updated link back.',
      'Up to 16 places and 40 voters in one round.',
      'Places aren’t looked up anywhere: a pasted link names the place and gives directions.',
    ],
    later: [{ label: 'One live link that updates for everyone', pro: false }],
  },
  {
    id: 'plan',
    slug: 'plan',
    name: 'Plan',
    kind: 'Group event card',
    tagline: 'What, when, where and who, on one shared card.',
    description:
      'Start with what it is (dinner, a birthday, a trip), name it, and add the day, the place and the people only if you know them. Everyone opens one link and taps if they’re in. When you need more, it connects: find a time with When?, vote on a place with Where?, share what to bring with Bring and split the bill after with Split.',
    category: 'together',
    family: 'gather',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['link', 'browser'],
      note: 'The plan and everyone’s answers travel inside the link. Hyphy’s servers never receive them.',
    },
    accent: '#4f7cff',
    accentInk: 'light',
    icon: 'party',
    keywords: [
      'plan a party',
      'event planner',
      'plan an event',
      'birthday party',
      'party planning',
      'rsvp',
      'gathering',
      'trip planning',
      'invite friends',
      'plan a dinner',
      'group trip',
      'who is coming',
      'event invite',
      'bbq',
      'plan a hangout',
      'concert night',
      'family event',
    ],
    aliases: ['partiful', 'evite', 'facebook event', 'paperless post'],
    related: ['when', 'where', 'bring', 'split'],
    fresh: true,
    featured: true,
    priority: 11,
    modes: {
      everyday: { rank: 2, line: 'Birthdays, dinners, weekends away' },
    },
    tier: 'experience',
    steps: [
      'Pick what it is and name it; add the day, place and people if you know them.',
      'Send the invite. People tap I’m in, Maybe or Can’t, and send it back.',
      'Need more? Find a time, vote on a place, list what to bring, split the bill after.',
    ],
    limits: [
      'The plan lives in its link: after answering, people send the updated link back.',
      'Connected tools attach by their links: open them from the plan to keep them together.',
      'Up to 60 people in one plan.',
    ],
    later: [{ label: 'One live link that updates for everyone', pro: false }],
  },

  /* ---------------- Signal ---------------- */
  {
    id: 'qr',
    slug: 'qr',
    name: 'QR Studio',
    kind: 'QR code maker',
    tagline: 'Codes for links, Wi-Fi, contacts and more — styled, and still scannable.',
    description:
      'Make a QR code for a link, your Wi-Fi, a contact card, a phone number, an email or a text. Style the dots, corners and colors, add a logo, and download a print-ready PNG or SVG.',
    category: 'links',
    family: 'signal',
    status: 'available',
    visibility: 'public',
    access: 'freemium',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Codes are drawn on your device. No tracking redirect is ever put inside your code.',
    },
    accent: '#3ee0d0',
    accentInk: 'dark',
    icon: 'qr',
    keywords: [
      'make a qr',
      'qr code',
      'qr code generator',
      'wifi qr',
      'wifi password',
      'share wifi',
      'contact qr',
      'vcard',
      'business card qr',
      'menu qr',
      'qr for a link',
      'qr with logo',
      'qr code for text',
      'scan code',
      'custom qr',
    ],
    aliases: ['qr generator', 'qr maker', 'qr monkey'],
    related: ['signal-links', 'signal-pages', 'palette'],
    featured: true,
    priority: 11,
    modes: {
      everyday: { rank: 4, line: 'Wi-Fi, sharing, events' },
      create: { rank: 4, line: 'Flyers, posts and designs' },
      work: { rank: 4, line: 'Menus, reviews, marketing' },
    },
    tier: 'tool',
    steps: [
      'Choose what the code opens: a link, Wi-Fi, a contact, a call, a text.',
      'Style it. Contrast and logo size are checked so it still scans.',
      'Download a sharp PNG or a vector SVG for print.',
    ],
    limits: [
      'Static codes: what’s printed can’t be changed later, and nothing is tracked.',
      'Logos need high error correction, which makes the code denser.',
    ],
    later: [{ label: 'Codes you can change after printing, with scan counts', pro: true }],
    spaces: 'qr',
  },
  {
    id: 'signal-pages',
    slug: 'signal-pages',
    name: 'Signal Pages',
    kind: 'Link-in-bio page',
    tagline: 'One page for everything you link to.',
    description:
      'Build a link-in-bio page with your name, links and socials, in a design that doesn’t look like everyone else’s. Share it as a link or print its QR code.',
    category: 'links',
    family: 'signal',
    status: 'beta',
    visibility: 'public',
    access: 'freemium',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['link', 'browser'],
      note: 'Your page is carried inside its own link, so Hyphy doesn’t store it. Anyone with the link can see it.',
    },
    accent: '#ff8ad8',
    accentInk: 'dark',
    icon: 'link',
    keywords: [
      'link in bio',
      'bio link',
      'link page',
      'links page',
      'instagram bio link',
      'tiktok bio link',
      'all my links',
      'one link for everything',
      'social links',
      'personal page',
      'landing page',
    ],
    aliases: ['linktree', 'beacons', 'link hub', 'lnk bio', 'carrd', 'bio site'],
    related: ['qr', 'signal-links', 'palette'],
    pick: true,
    priority: 15,
    modes: {
      create: { rank: 7, line: 'One link for everything you make' },
      work: { rank: 7, line: 'A page for your business' },
    },
    tier: 'experience',
    steps: [
      'Tap your name, bio and links on the phone to edit them.',
      'Pick a design and add your socials.',
      'Share the page’s link, or print its QR code.',
    ],
    limits: [
      'Your page lives in a long link for now. A short address arrives with accounts.',
      'Up to 12 links and 8 socials.',
    ],
    later: [
      { label: 'A short, custom address for your page', pro: false },
      { label: 'Click counts for every link', pro: true },
      { label: 'Photos, embeds and more designs', pro: true },
    ],
    spaces: 'links',
  },
  {
    id: 'signal-links',
    slug: 'signal-links',
    name: 'Signal Links',
    kind: 'Campaign link builder',
    tagline: 'Make a link that tells you where your visitors came from.',
    description:
      'Turn any link into a trackable campaign link for a post, an email or a flyer. Your analytics can then show which one actually brought people in. Plain words first, the technical fields when you want them.',
    category: 'links',
    family: 'signal',
    status: 'available',
    visibility: 'public',
    access: 'freemium',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['browser'],
      note: 'Links are built on your device. The link you’re making and your recent links are remembered in this browser only.',
    },
    accent: '#f2d7a6',
    accentInk: 'dark',
    icon: 'link-2',
    keywords: [
      'utm',
      'utm builder',
      'utm generator',
      'utm link',
      'campaign link',
      'tracking link',
      'trackable link',
      'track a link',
      'google analytics link',
      'track clicks',
      'marketing link',
      'source medium campaign',
      'where did visitors come from',
    ],
    aliases: ['campaign url builder', 'url builder', 'utm.io'],
    related: ['qr', 'signal-pages', 'social-crop'],
    fresh: true,
    priority: 30,
    modes: {
      create: { rank: 8, line: 'Know which post worked' },
      work: { rank: 5, line: 'Track every campaign link' },
    },
    tier: 'tool',
    steps: [
      'Paste the page you’re sending people to.',
      'Say where the link will live: an Instagram post, a newsletter, a flyer.',
      'Copy the finished link, or turn it into a QR code.',
    ],
    limits: [
      'Tracking shows up in your own analytics (like Google Analytics). Hyphy doesn’t count clicks.',
      'Doesn’t shorten links yet.',
    ],
    later: [{ label: 'Short links with click counts', pro: true }],
  },

  /* ---------------- File Lab ---------------- */
  {
    id: 'pdf',
    slug: 'pdf',
    name: 'PDF',
    kind: 'PDF toolkit',
    tagline: 'Merge, split, reorder, rotate and pull out pages.',
    description:
      'Combine PDFs, keep only the pages you need, split one into several, or fix the order and the sideways scans, with every page shown as it really looks.',
    category: 'files',
    family: 'file-lab',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Your PDFs are opened and rebuilt in your browser. They’re never uploaded.',
    },
    accent: '#ff6a3d',
    accentInk: 'dark',
    icon: 'pdf',
    keywords: [
      'merge pdf',
      'combine pdf',
      'join pdf',
      'split pdf',
      'extract pages',
      'remove pages from pdf',
      'delete pdf pages',
      'rotate pdf',
      'reorder pdf pages',
      'organize pdf',
      'pdf pages',
      'one pdf',
    ],
    aliases: ['ilovepdf', 'smallpdf', 'pdf merge', 'pdf splitter', 'adobe acrobat'],
    related: ['convert', 'clean', 'duplicates'],
    pick: true,
    priority: 13,
    modes: {
      everyday: { rank: 6, line: 'Forms, tickets, paperwork' },
      create: { rank: 5, line: 'Portfolios and printables' },
      work: { rank: 3, line: 'Merge, reorder, ready to send' },
    },
    tier: 'tool',
    steps: [
      'Choose what to do: merge, organize, keep pages or split.',
      'Drop in your PDFs and see every page.',
      'Download the new PDF.',
    ],
    limits: [
      'Up to 20 files, 50 MB and 500 pages at a time.',
      'Pages are copied as they are: form fields, bookmarks and signatures may not carry over.',
      'Password-protected PDFs can’t be opened.',
    ],
    later: [],
    spaces: 'pdf',
  },
  {
    id: 'convert',
    slug: 'convert',
    name: 'Convert',
    kind: 'File converter',
    tagline: 'Photos into a PDF, PDF pages into images, PNG into WebP.',
    description:
      'Turn photos and scans into a single PDF, in the order you choose, turn the pages of a PDF into sharp JPG or PNG images, or change photos between JPG, PNG and WebP.',
    category: 'files',
    family: 'file-lab',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Converted in your browser. Nothing is uploaded, and camera details and location are left out of the PDF.',
    },
    accent: '#6a84ff',
    accentInk: 'dark',
    icon: 'file-stack',
    keywords: [
      'jpg to pdf',
      'image to pdf',
      'photos to pdf',
      'png to pdf',
      'scan to pdf',
      'pdf to jpg',
      'pdf to image',
      'pdf to png',
      'convert pdf',
      'convert images',
      'make a pdf',
    ],
    aliases: ['img2pdf'],
    related: ['pdf', 'resize', 'clean'],
    fresh: true,
    priority: 32,
    modes: {
      everyday: { rank: 11, line: 'HEIC to JPG, photos to PDF' },
      create: { rank: 6, line: 'Any format you need' },
      work: { rank: 8, line: 'Scans and photos into one PDF' },
    },
    tier: 'tool',
    steps: [
      'Choose a direction: images to PDF, or PDF to images.',
      'Add your files and put them in order.',
      'Download the PDF, or the images in one zip.',
    ],
    limits: [
      'Reads JPG, PNG, WebP, GIF and AVIF. iPhone HEIC photos open only in Safari.',
      'Up to 60 images (40 MB each), or one PDF of up to 200 pages and 50 MB.',
      'Password-protected PDFs can’t be opened.',
      'Page images are pictures: links, forms and selectable text don’t carry over.',
    ],
    later: [],
  },
  {
    id: 'clean',
    slug: 'clean',
    name: 'Clean',
    kind: 'Bulk file renamer',
    tagline: 'Rename a pile of files at once, and see every new name first.',
    description:
      'Clean up file names with find and replace, numbering, prefixes, dates and tidy capitalization. Every new name is previewed before anything happens, then you download renamed copies in one zip.',
    category: 'files',
    family: 'file-lab',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Your files are read and zipped in your browser. They’re never uploaded.',
    },
    accent: '#c7b5ff',
    accentInk: 'dark',
    icon: 'replace',
    keywords: [
      'rename files',
      'bulk rename',
      'batch rename',
      'rename photos',
      'rename many files',
      'file names',
      'clean up file names',
      'clean some files',
      'number files',
      'find and replace file names',
      'lowercase file names',
      'remove spaces from file names',
      'img files',
    ],
    aliases: ['bulk rename utility', 'renamer', 'file renamer', 'advanced renamer'],
    related: ['duplicates', 'pdf', 'convert'],
    fresh: true,
    priority: 31,
    modes: {
      everyday: { rank: 13, line: 'Tidy a messy folder' },
      create: { rank: 10, line: 'Name a whole shoot at once' },
      work: { rank: 9, line: 'Files named the way you file' },
    },
    tier: 'tool',
    steps: [
      'Choose your files, or a whole folder.',
      'Stack up rules: replace, number, add a date, fix capitals.',
      'Check every new name, then download the renamed copies.',
    ],
    limits: [
      'Browsers can’t rename files where they sit, so you download renamed copies in a zip.',
      'Up to 1,000 files and 1 GB at a time.',
      'Dates come from each file’s last-modified time, which isn’t always when a photo was taken.',
    ],
    later: [],
  },
  {
    id: 'duplicates',
    slug: 'duplicates',
    name: 'Duplicates',
    kind: 'Duplicate file finder',
    tagline: 'Find the files you have twice.',
    description:
      'Choose a folder or a pile of files and Duplicates finds exact copies by what’s inside them, even when the names are different, and shows how much space they take.',
    category: 'files',
    family: 'file-lab',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Files are fingerprinted in your browser. Nothing is uploaded, and nothing is deleted.',
    },
    accent: '#ffa24c',
    accentInk: 'dark',
    icon: 'copy',
    keywords: [
      'duplicate files',
      'find duplicates',
      'duplicate photos',
      'same file twice',
      'remove duplicates',
      'free up space',
      'dedupe',
      'identical files',
      'copies of files',
      'find copies',
    ],
    aliases: ['dupeguru', 'gemini duplicate finder'],
    related: ['clean', 'resize', 'pdf'],
    fresh: true,
    priority: 33,
    modes: {
      everyday: { rank: 14, line: 'Free up space' },
      create: { rank: 9, line: 'Find the copies in a shoot' },
      work: { rank: 11, line: 'Clear out the shared drive' },
    },
    tier: 'tool',
    steps: [
      'Choose a folder, or select a pile of files.',
      'Duplicates compares what’s inside each file.',
      'See every group of copies and download the list.',
    ],
    limits: [
      'Checks only the files you choose. It can’t scan your whole computer.',
      'Finds exact copies. Photos that only look alike come later.',
      'It never deletes anything. You get a clear list to clean up yourself.',
      'Files over 2 GB can’t be read in a browser. When two share a size, they’re listed for you to compare by hand.',
    ],
    later: [{ label: 'Photos that look alike, not just exact copies', pro: false }],
  },

  /* ---------------- Image Lab ---------------- */
  {
    id: 'resize',
    slug: 'resize',
    name: 'Resize & Compress',
    kind: 'Image resizer and compressor',
    tagline: 'Smaller files. Same picture.',
    description:
      'Resize, compress and convert photos to JPG, PNG or WebP, and see the new size before you download. A file never comes back bigger than it went in.',
    category: 'images',
    family: 'image-lab',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Photos are processed in your browser. Saved copies leave out camera and location data.',
    },
    accent: '#ffc53d',
    accentInk: 'dark',
    icon: 'image',
    keywords: [
      'resize photos',
      'resize image',
      'compress image',
      'compress photos',
      'reduce image size',
      'make photo smaller',
      'shrink photo',
      'image file size',
      'convert image',
      'jpg to webp',
      'png to jpg',
      'optimize images',
      'photo too big',
    ],
    aliases: ['tinypng', 'squoosh', 'image compressor', 'image resize'],
    related: ['social-crop', 'palette', 'convert'],
    priority: 16,
    modes: {
      everyday: { rank: 5, line: 'Too big to send? Fixed.' },
      create: { rank: 2, line: 'The right size, still sharp' },
      work: { rank: 12, line: 'Photos light enough to email' },
    },
    tier: 'tool',
    steps: [
      'Drop in up to 20 photos.',
      'Pick a width, a format and a quality.',
      'Compare the sizes, then download.',
    ],
    limits: ['Up to 20 images at a time, 40 MB each.', 'Images are never enlarged.'],
    later: [],
    spaces: 'images',
  },
  {
    id: 'social-crop',
    slug: 'social-crop',
    name: 'Social Crop',
    kind: 'Social media image sizes',
    tagline: 'One photo, framed for every feed.',
    description:
      'Add a photo once and frame it for Instagram, Stories, TikTok, YouTube, X and LinkedIn. Drag and zoom to compose each size, then download one or all of them.',
    category: 'images',
    family: 'image-lab',
    status: 'available',
    visibility: 'public',
    access: 'freemium',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Your photo is framed and exported in your browser. It’s never uploaded.',
    },
    accent: '#9b86ff',
    accentInk: 'dark',
    icon: 'crop',
    keywords: [
      'instagram size',
      'instagram post size',
      'instagram story size',
      'crop for instagram',
      'tiktok size',
      'youtube thumbnail',
      'social media sizes',
      'resize for social media',
      'reel cover',
      'linkedin banner',
      'x header',
      'twitter header',
      'crop photo',
      'crop image',
      'aspect ratio',
      'square photo',
      'profile picture',
    ],
    aliases: ['social image resizer', 'crop tool'],
    related: ['resize', 'palette', 'signal-links'],
    featured: true,
    fresh: true,
    priority: 17,
    modes: {
      create: { rank: 1, line: 'Every feed, one photo' },
    },
    tier: 'tool',
    steps: [
      'Add one photo.',
      'Pick the sizes you need and drag each frame to compose it.',
      'Download one, or all of them in a zip.',
    ],
    limits: [
      'Cropping removes what falls outside a frame. Fit mode keeps it all, with a soft backdrop.',
      'Exports JPG or PNG at each network’s recommended size.',
    ],
    later: [
      { label: 'AI Expand: grow a photo to fit a new shape instead of cropping it', pro: true },
    ],
  },
  {
    id: 'palette',
    slug: 'palette',
    name: 'Palette',
    kind: 'Color palette extractor',
    tagline: 'Pull the colors out of any image.',
    description:
      'Drop in a photo or a logo and get its key colors as HEX and RGB, ready-to-paste CSS variables, and which pairs are readable together.',
    category: 'images',
    family: 'image-lab',
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['none'],
      note: 'Colors are measured in your browser. Your image is never uploaded.',
    },
    accent: '#ff7ab6',
    accentInk: 'dark',
    icon: 'palette',
    keywords: [
      'color palette',
      'colors from image',
      'colors from logo',
      'hex codes',
      'hex color',
      'brand colors',
      'extract colors',
      'color picker',
      'css variables',
      'color scheme',
      'rgb values',
      'what color is this',
    ],
    aliases: ['coolors', 'adobe color', 'eyedropper', 'colorthief'],
    related: ['qr', 'signal-pages', 'social-crop'],
    fresh: true,
    priority: 18,
    modes: {
      create: { rank: 3, line: 'Colors straight out of a photo' },
    },
    tier: 'tool',
    steps: [
      'Drop in a photo or a logo.',
      'Get its key colors, strongest first.',
      'Copy HEX, RGB, HSL, CSS or a Tailwind theme, or download the swatches.',
    ],
    limits: [
      'Finds up to 10 key colors. Tiny details may not make the cut, so tap the image to add them.',
    ],
    later: [],
  },

  /* ---------------- Drops ---------------- */
  {
    id: 'wishlist',
    slug: 'christmas-list',
    name: 'Christmas List',
    kind: 'Shareable wish list',
    tagline: 'A wish list that quietly stops duplicate gifts.',
    description:
      'Make a list with links, prices and notes. Family and friends claim what they’re buying, and you never see who got what, so the surprise survives.',
    category: 'together',
    drop: {
      season: 'Holiday 2026',
      line: 'For everyone who has ever received two identical sweaters.',
    },
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['link', 'browser'],
      note: 'The list and the claims travel inside links. Hyphy’s servers never receive them.',
    },
    accent: '#ff5e57',
    accentInk: 'dark',
    icon: 'gift',
    keywords: [
      'christmas list',
      'wish list',
      'wishlist',
      'gift list',
      'gift ideas',
      'birthday wishlist',
      'holiday list',
      'present list',
      'santa list',
      'who is buying what',
      'registry',
      'gift registry',
    ],
    aliases: ['giftster', 'elfster', 'amazon wishlist'],
    related: ['secret-santa', 'bring', 'split'],
    featured: true,
    fresh: true,
    priority: 19,
    modes: {
      everyday: { rank: 10, line: 'Gifts nobody doubles up on' },
    },
    tier: 'experience',
    steps: [
      'Add what you’d love: a link, a price, a note, how much you want it.',
      'Share the gift-giver link with family and friends, not with yourself.',
      'They claim gifts; your own link never shows who claimed what.',
    ],
    limits: [
      'Claims live in the gift-giver link: after claiming, givers pass the updated link along.',
      'Up to 60 items in one list.',
    ],
    later: [{ label: 'One live list that updates for everyone', pro: false }],
  },
  {
    id: 'secret-santa',
    slug: 'secret-santa',
    name: 'Secret Santa',
    kind: 'Gift exchange draw',
    tagline: 'Draw names without a hat, or spoilers.',
    description:
      'Add everyone, keep couples from drawing each other, pick a budget if you want one, and draw. Each person gets a private link with one envelope inside: their match, the budget, the day and your note. Nobody sees anyone else’s, the organizer included.',
    category: 'together',
    drop: { season: 'Holiday 2026', line: 'Drawing names, minus the hat.' },
    status: 'available',
    visibility: 'public',
    access: 'free',
    account: 'none',
    privacy: {
      processing: 'device',
      storage: ['browser', 'link'],
      note: 'Names are drawn on your device. The draw stays in your browser; each private link carries only that person’s match. Hyphy’s servers never receive any of it.',
    },
    accent: '#c23a4b',
    accentInk: 'light',
    icon: 'gift',
    keywords: [
      'secret santa',
      'gift exchange',
      'draw names',
      'white elephant',
      'kris kringle',
      'name draw',
      'secret santa generator',
      'pick names from a hat',
      'office gift exchange',
      'family gift exchange',
      'holiday exchange',
    ],
    aliases: ['elfster', 'drawnames', 'secret santa organizer'],
    related: ['wishlist', 'plan', 'bring'],
    fresh: true,
    priority: 20,
    modes: {
      everyday: { rank: 9, line: 'Draw names, keep the secret' },
    },
    tier: 'experience',
    steps: [
      'Add everyone: type names or paste a list.',
      'Keep couples or housemates apart, and pick a budget if you like.',
      'Draw, then send each person their private envelope link.',
    ],
    limits: [
      'The draw is kept in the organizer’s browser: send the links from the device that drew.',
      'Opening someone else’s link shows their match, so pass links on without opening them.',
      'Up to 60 people in one exchange.',
    ],
    later: [],
  },
];
